FROM tomcat:7.0
MAINTAINER dockerpractice
ADD http://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/war-stable/2.46.1/jenkins.war /usr/local/tomcat/webapps/jenkins.war/
COPY sample.war /usr/local/tomcat/webapps/sample.war
ENV CATALINA_HOME /usr/local/tomcat/
ENV PATH $CATALINA_HOME/bin:$PATH
RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME
RUN apt-get update 
EXPOSE 8080
CMD ["catalina.sh", "run"]


